import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-light": "#3B6939",
        "success-light-on": "#FFFFFF",
        "success-light-container": "#BCF0B4",
        "success-light-on-container": "#002204",
        "success-dark": "#A1D39A",
        "success-dark-on": "#0A390F",
        "success-dark-container": "#235024",
        "success-dark-on-container": "#BCF0B4",
        "warning-light": "#775A0B",
        "warning-light-on": "#FFFFFF",
        "warning-light-container": "#FFDF9E",
        "warning-light-on-container": "#261A00",
        "warning-dark": "#E9C16C",
        "warning-dark-on": "#3F2E00",
        "warning-dark-container": "#5B4300",
        "warning-dark-on-container": "#FFDF9E",
        "info-light": "#36618E",
        "info-light-on": "#FFFFFF",
        "info-light-container": "#D1E4FF",
        "info-light-on-container": "#001D36",
        "info-dark": "#A0CAFD",
        "info-dark-on": "#003258",
        "info-dark-container": "#194975",
        "info-dark-on-container": "#D1E4FF",
        "attention-light": "#685F12",
        "attention-light-on": "#FFFFFF",
        "attention-light-container": "#F1E48A",
        "attention-light-on-container": "#201C00",
        "attention-dark": "#D4C871",
        "attention-dark-on": "#363100",
        "attention-dark-container": "#4F4800",
        "attention-dark-on-container": "#F1E48A",
        "error-light": "#B3261E",
        "error-light-on": "#FFFFFF",
        "error-light-container": "#FFDAD6",
        "error-light-on-container": "#410002",
        "error-dark": "#FFB4AB",
        "error-dark-on": "#690005",
        "error-dark-container": "#93000A",
        light: {
          primary: "#4F46E5",
          surfaceTint: "#4F46E5",
          onPrimary: "#FFFFFF",
          primaryContainer: "#E0E7FF",
          onPrimaryContainer: "#3730A3",
          secondary: "#6366F1",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#E0E7FF",
          onSecondaryContainer: "#3730A3",
          tertiary: "#7C3AED",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#F3E8FF",
          onTertiaryContainer: "#5B21B6",
          error: "#BA1A1A",
          onError: "#FFFFFF",
          errorContainer: "#FFDAD6",
          onErrorContainer: "#93000A",
          background: "#F8F9FF",
          onBackground: "#0A1829",
          surface: "#F8F9FF",
          onSurface: "#0A1829",
          surfaceVariant: "#E0E7FF",
          onSurfaceVariant: "#47408D",
          outline: "#6F7A99",
          outlineVariant: "#C7C7FF",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#0F1E2F",
          inverseOnSurface: "#EFF1FF",
          inversePrimary: "#C7D2FF",
          primaryFixed: "#E0E7FF",
          onPrimaryFixed: "#3730A3",
          primaryFixedDim: "#C7D2FF",
          onPrimaryFixedVariant: "#3730A3",
          secondaryFixed: "#E0E7FF",
          onSecondaryFixed: "#3730A3",
          secondaryFixedDim: "#C7D2FF",
          onSecondaryFixedVariant: "#3730A3",
          tertiaryFixed: "#F3E8FF",
          onTertiaryFixed: "#5B21B6",
          tertiaryFixedDim: "#E9D5FF",
          onTertiaryFixedVariant: "#5B21B6",
          surfaceDim: "#D8DCE8",
          surfaceBright: "#F8F9FF",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F2F3FF",
          surfaceContainer: "#ECF0FF",
          surfaceContainerHigh: "#E6EAFF",
          surfaceContainerHighest: "#E0E5FF",
        },
        "light-medium-contrast": {
          primary: "#3F37C9",
          surfaceTint: "#4F46E5",
          onPrimary: "#FFFFFF",
          primaryContainer: "#6B63FF",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#4F46E5",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#6B63FF",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#6D28D9",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#8B5CF6",
          onTertiaryContainer: "#FFFFFF",
          error: "#8C0009",
          onError: "#FFFFFF",
          errorContainer: "#DA342E",
          onErrorContainer: "#FFFFFF",
          background: "#F8F9FF",
          onBackground: "#0A1829",
          surface: "#F8F9FF",
          onSurface: "#050D1C",
          surfaceVariant: "#E0E7FF",
          onSurfaceVariant: "#36378F",
          outline: "#4D5885",
          outlineVariant: "#5B60B0",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#0F1E2F",
          inverseOnSurface: "#EFF1FF",
          inversePrimary: "#D0D9FF",
          primaryFixed: "#6B63FF",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#3F37C9",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#6B63FF",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#4F46E5",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#8B5CF6",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#6D28D9",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#C1C5D1",
          surfaceBright: "#F8F9FF",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F2F3FF",
          surfaceContainer: "#E6EAFF",
          surfaceContainerHigh: "#DFE2FF",
          surfaceContainerHighest: "#D8DBFF",
        },
        "light-high-contrast": {
          primary: "#220096",
          surfaceTint: "#4F46E5",
          onPrimary: "#FFFFFF",
          primaryContainer: "#3F37C9",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#1E00FF",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#3F37C9",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#3F0080",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#6D28D9",
          onTertiaryContainer: "#FFFFFF",
          error: "#600004",
          onError: "#FFFFFF",
          errorContainer: "#8C0009",
          onErrorContainer: "#FFFFFF",
          background: "#F8F9FF",
          onBackground: "#000000",
          surface: "#F8F9FF",
          onSurface: "#000000",
          surfaceVariant: "#E0E7FF",
          onSurfaceVariant: "#000000",
          outline: "#1F2A50",
          outlineVariant: "#36378F",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#0F1E2F",
          inverseOnSurface: "#FFFFFF",
          inversePrimary: "#D0D9FF",
          primaryFixed: "#3F37C9",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#2E1FB5",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#3F37C9",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#2E1FB5",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#6D28D9",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#5E21B6",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#B5B9C5",
          surfaceBright: "#F8F9FF",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#EFF1FF",
          surfaceContainer: "#DFE2FF",
          surfaceContainerHigh: "#D3D6FF",
          surfaceContainerHighest: "#C7CAFF",
        },
        dark: {
          primary: "#C7D2FF",
          surfaceTint: "#C7D2FF",
          onPrimary: "#1A0E7F",
          primaryContainer: "#3F37C9",
          onPrimaryContainer: "#E0E7FF",
          secondary: "#C7D2FF",
          onSecondary: "#1A0E7F",
          secondaryContainer: "#4F46E5",
          onSecondaryContainer: "#E0E7FF",
          tertiary: "#E9D5FF",
          onTertiary: "#3F0080",
          tertiaryContainer: "#6D28D9",
          onTertiaryContainer: "#F3E8FF",
          error: "#FFB4AB",
          onError: "#690005",
          errorContainer: "#93000A",
          onErrorContainer: "#FFDAD6",
          background: "#0A0E1F",
          onBackground: "#E8EAFF",
          surface: "#0A0E1F",
          onSurface: "#E8EAFF",
          surfaceVariant: "#47408D",
          onSurfaceVariant: "#C7C7FF",
          outline: "#8B8FD9",
          outlineVariant: "#47408D",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E8EAFF",
          inverseOnSurface: "#1F2949",
          inversePrimary: "#4F46E5",
          primaryFixed: "#E0E7FF",
          onPrimaryFixed: "#1A0E7F",
          primaryFixedDim: "#C7D2FF",
          onPrimaryFixedVariant: "#3F37C9",
          secondaryFixed: "#E0E7FF",
          onSecondaryFixed: "#1A0E7F",
          secondaryFixedDim: "#C7D2FF",
          onSecondaryFixedVariant: "#3F37C9",
          tertiaryFixed: "#F3E8FF",
          onTertiaryFixed: "#3F0080",
          tertiaryFixedDim: "#E9D5FF",
          onTertiaryFixedVariant: "#6D28D9",
          surfaceDim: "#0A0E1F",
          surfaceBright: "#30354D",
          surfaceContainerLowest: "#050909",
          surfaceContainerLow: "#131828",
          surfaceContainer: "#1A2031",
          surfaceContainerHigh: "#25293F",
          surfaceContainerHighest: "#30354D",
        },
        "dark-medium-contrast": {
          primary: "#D0D9FF",
          surfaceTint: "#C7D2FF",
          onPrimary: "#140068",
          primaryContainer: "#6B63FF",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#D0D9FF",
          onSecondary: "#140068",
          secondaryContainer: "#6B63FF",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#F0E9FF",
          onTertiary: "#2A0066",
          tertiaryContainer: "#8B5CF6",
          onTertiaryContainer: "#FFFFFF",
          error: "#FFD2CC",
          onError: "#540003",
          errorContainer: "#FF5449",
          onErrorContainer: "#000000",
          background: "#0A0E1F",
          onBackground: "#E8EAFF",
          surface: "#0A0E1F",
          onSurface: "#FFFFFF",
          surfaceVariant: "#47408D",
          onSurfaceVariant: "#D1CCFF",
          outline: "#9FA5D9",
          outlineVariant: "#7B7BB8",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E8EAFF",
          inverseOnSurface: "#14182F",
          inversePrimary: "#3F37C9",
          primaryFixed: "#E0E7FF",
          onPrimaryFixed: "#140068",
          primaryFixedDim: "#C7D2FF",
          onPrimaryFixedVariant: "#3F37C9",
          secondaryFixed: "#E0E7FF",
          onSecondaryFixed: "#140068",
          secondaryFixedDim: "#C7D2FF",
          onSecondaryFixedVariant: "#3F37C9",
          tertiaryFixed: "#F3E8FF",
          onTertiaryFixed: "#2A0066",
          tertiaryFixedDim: "#E9D5FF",
          onTertiaryFixedVariant: "#6D28D9",
          surfaceDim: "#0A0E1F",
          surfaceBright: "#3C4257",
          surfaceContainerLowest: "#040808",
          surfaceContainerLow: "#181F1F",
          surfaceContainer: "#232929",
          surfaceContainerHigh: "#2D3434",
          surfaceContainerHighest: "#383F3F",
        },
        "dark-high-contrast": {
          primary: "#EFF1FF",
          surfaceTint: "#C7D2FF",
          onPrimary: "#000000",
          primaryContainer: "#9B99FF",
          onPrimaryContainer: "#000000",
          secondary: "#EFF1FF",
          onSecondary: "#000000",
          secondaryContainer: "#9B99FF",
          onSecondaryContainer: "#000000",
          tertiary: "#FFF0FF",
          onTertiary: "#000000",
          tertiaryContainer: "#C9A3E9",
          onTertiaryContainer: "#000000",
          error: "#FFECE9",
          onError: "#000000",
          errorContainer: "#FFAEA4",
          onErrorContainer: "#000000",
          background: "#0C1410",
          onBackground: "#DDE7E1",
          surface: "#0C1410",
          onSurface: "#FFFFFF",
          surfaceVariant: "#47408D",
          onSurfaceVariant: "#FFFFFF",
          outline: "#E0DDFF",
          outlineVariant: "#B9B5FF",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#DDE7E1",
          inverseOnSurface: "#000000",
          inversePrimary: "#220096",
          primaryFixed: "#E0E7FF",
          onPrimaryFixed: "#000000",
          primaryFixedDim: "#C7D2FF",
          onPrimaryFixedVariant: "#220096",
          secondaryFixed: "#E0E7FF",
          onSecondaryFixed: "#000000",
          secondaryFixedDim: "#C7D2FF",
          onSecondaryFixedVariant: "#1E00FF",
          tertiaryFixed: "#F3E8FF",
          onTertiaryFixed: "#000000",
          tertiaryFixedDim: "#E9D5FF",
          onTertiaryFixedVariant: "#3F0080",
          surfaceDim: "#0C1410",
          surfaceBright: "#4C5550",
          surfaceContainerLowest: "#000000",
          surfaceContainerLow: "#1A2420",
          surfaceContainer: "#2C3530",
          surfaceContainerHigh: "#37403B",
          surfaceContainerHighest: "#424B46",
        },
      },
      fontSize: {
        "display-large": [
          "57px",
          {
            lineHeight: "64px",
          },
        ],
        "display-medium": [
          "45px",
          {
            lineHeight: "52px",
          },
        ],
        "display-small": [
          "36px",
          {
            lineHeight: "44px",
          },
        ],
        "headline-large": [
          "32px",
          {
            lineHeight: "40px",
          },
        ],
        "headline-medium": [
          "28px",
          {
            lineHeight: "36px",
          },
        ],
        "headline-small": [
          "24px",
          {
            lineHeight: "32px",
          },
        ],
        "title-large": [
          "22px",
          {
            lineHeight: "28px",
          },
        ],
        "title-medium": [
          "16px",
          {
            lineHeight: "24px",
          },
        ],
        "title-small": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "body-large": [
          "16px",
          {
            lineHeight: "24px",
          },
        ],
        "body-medium": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "body-small": [
          "12px",
          {
            lineHeight: "16px",
          },
        ],
        "label-large": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "label-medium": [
          "12px",
          {
            lineHeight: "16px",
          },
        ],
        "label-small": [
          "11px",
          {
            lineHeight: "16px",
          },
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      screens: {
        custom: "1100px",
        resultaHidden: "766px",
        lgMin: "947px",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("@tailwindcss/typography")],
} satisfies Config;
