import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "success-light": "#3B6939",
        "success-light-on": "#FFFFFF",
        "success-light-container": "#BCF0B4",
        "success-light-on-container": "#002204",
        "success-dark": "#A1D39A",
        "success-dark-on": "#0A390F",
        "success-dark-container": "#235024",
        "success-dark-on-container": "#BCF0B4",
        "warning-light": "#775A0B",
        "warning-light-on": "#FFFFFF",
        "warning-light-container": "#FFDF9E",
        "warning-light-on-container": "#261A00",
        "warning-dark": "#E9C16C",
        "warning-dark-on": "#3F2E00",
        "warning-dark-container": "#5B4300",
        "warning-dark-on-container": "#FFDF9E",
        "info-light": "#36618E",
        "info-light-on": "#FFFFFF",
        "info-light-container": "#D1E4FF",
        "info-light-on-container": "#001D36",
        "info-dark": "#A0CAFD",
        "info-dark-on": "#003258",
        "info-dark-container": "#194975",
        "info-dark-on-container": "#D1E4FF",
        "attention-light": "#685F12",
        "attention-light-on": "#FFFFFF",
        "attention-light-container": "#F1E48A",
        "attention-light-on-container": "#201C00",
        "attention-dark": "#D4C871",
        "attention-dark-on": "#363100",
        "attention-dark-container": "#4F4800",
        "attention-dark-on-container": "#F1E48A",
        "error-light": "#B3261E",
        "error-light-on": "#FFFFFF",
        "error-light-container": "#FFDAD6",
        "error-light-on-container": "#410002",
        "error-dark": "#FFB4AB",
        "error-dark-on": "#690005",
        "error-dark-container": "#93000A",
        light: {
          primary: "#0066CC",
          surfaceTint: "#0066CC",
          onPrimary: "#FFFFFF",
          primaryContainer: "#CCE5FF",
          onPrimaryContainer: "#001947",
          secondary: "#0D5FB3",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#D9E2FF",
          onSecondaryContainer: "#001A41",
          tertiary: "#4A5FB8",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#E0E0FF",
          onTertiaryContainer: "#050061",
          error: "#BA1A1A",
          onError: "#FFFFFF",
          errorContainer: "#FFDAD6",
          onErrorContainer: "#93000A",
          background: "#F8F9FF",
          onBackground: "#0A1829",
          surface: "#F8F9FF",
          onSurface: "#0A1829",
          surfaceVariant: "#D9E2FF",
          onSurfaceVariant: "#3E4A70",
          outline: "#6F7A99",
          outlineVariant: "#C3CDEE",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#0F1E2F",
          inverseOnSurface: "#EFF1FF",
          inversePrimary: "#99CCFF",
          primaryFixed: "#CCE5FF",
          onPrimaryFixed: "#001947",
          primaryFixedDim: "#99CCFF",
          onPrimaryFixedVariant: "#004399",
          secondaryFixed: "#D9E2FF",
          onSecondaryFixed: "#001A41",
          secondaryFixedDim: "#ADD8FF",
          onSecondaryFixedVariant: "#0A4698",
          tertiaryFixed: "#E0E0FF",
          onTertiaryFixed: "#050061",
          tertiaryFixedDim: "#C5C6FF",
          onTertiaryFixedVariant: "#3649A0",
          surfaceDim: "#D8DCE8",
          surfaceBright: "#F8F9FF",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F2F3FF",
          surfaceContainer: "#ECF0FF",
          surfaceContainerHigh: "#E6EAFF",
          surfaceContainerHighest: "#E0E5FF",
        },
        "light-medium-contrast": {
          primary: "#0052B3",
          surfaceTint: "#0066CC",
          onPrimary: "#FFFFFF",
          primaryContainer: "#3D7FFF",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#0A4FA3",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#3D7FD4",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#3149A8",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#6B7DCF",
          onTertiaryContainer: "#FFFFFF",
          error: "#8C0009",
          onError: "#FFFFFF",
          errorContainer: "#DA342E",
          onErrorContainer: "#FFFFFF",
          background: "#F8F9FF",
          onBackground: "#0A1829",
          surface: "#F8F9FF",
          onSurface: "#050D1C",
          surfaceVariant: "#D9E2FF",
          onSurfaceVariant: "#2D386F",
          outline: "#4D5885",
          outlineVariant: "#6B7A9B",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#0F1E2F",
          inverseOnSurface: "#EFF1FF",
          inversePrimary: "#99CCFF",
          primaryFixed: "#3D7FFF",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#0052B3",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#3D7FD4",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#0A4FA3",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#6B7DCF",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#3149A8",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#C1C5D1",
          surfaceBright: "#F8F9FF",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#F2F3FF",
          surfaceContainer: "#E6EAFF",
          surfaceContainerHigh: "#DFE2FF",
          surfaceContainerHighest: "#D8DBFF",
        },
        "light-high-contrast": {
          primary: "#002699",
          surfaceTint: "#0066CC",
          onPrimary: "#FFFFFF",
          primaryContainer: "#0052B3",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#042A8C",
          onSecondary: "#FFFFFF",
          secondaryContainer: "#0A4FA3",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#1A2F8F",
          onTertiary: "#FFFFFF",
          tertiaryContainer: "#3149A8",
          onTertiaryContainer: "#FFFFFF",
          error: "#600004",
          onError: "#FFFFFF",
          errorContainer: "#8C0009",
          onErrorContainer: "#FFFFFF",
          background: "#F8F9FF",
          onBackground: "#000000",
          surface: "#F8F9FF",
          onSurface: "#000000",
          surfaceVariant: "#D9E2FF",
          onSurfaceVariant: "#000000",
          outline: "#1F2A50",
          outlineVariant: "#2D386F",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#0F1E2F",
          inverseOnSurface: "#FFFFFF",
          inversePrimary: "#99CCFF",
          primaryFixed: "#0052B3",
          onPrimaryFixed: "#FFFFFF",
          primaryFixedDim: "#003D99",
          onPrimaryFixedVariant: "#FFFFFF",
          secondaryFixed: "#0A4FA3",
          onSecondaryFixed: "#FFFFFF",
          secondaryFixedDim: "#023578",
          onSecondaryFixedVariant: "#FFFFFF",
          tertiaryFixed: "#3149A8",
          onTertiaryFixed: "#FFFFFF",
          tertiaryFixedDim: "#1A2F8F",
          onTertiaryFixedVariant: "#FFFFFF",
          surfaceDim: "#B5B9C5",
          surfaceBright: "#F8F9FF",
          surfaceContainerLowest: "#FFFFFF",
          surfaceContainerLow: "#EFF1FF",
          surfaceContainer: "#DFE2FF",
          surfaceContainerHigh: "#D3D6FF",
          surfaceContainerHighest: "#C7CAFF",
        },
        dark: {
          primary: "#99CCFF",
          surfaceTint: "#99CCFF",
          onPrimary: "#001F4D",
          primaryContainer: "#0052B3",
          onPrimaryContainer: "#CCE5FF",
          secondary: "#ADD8FF",
          onSecondary: "#001F47",
          secondaryContainer: "#0A4FA3",
          onSecondaryContainer: "#D9E2FF",
          tertiary: "#C5C6FF",
          onTertiary: "#161C76",
          tertiaryContainer: "#3149A8",
          onTertiaryContainer: "#E0E0FF",
          error: "#FFB4AB",
          onError: "#690005",
          errorContainer: "#93000A",
          onErrorContainer: "#FFDAD6",
          background: "#0A0E1F",
          onBackground: "#E8EAFF",
          surface: "#0A0E1F",
          onSurface: "#E8EAFF",
          surfaceVariant: "#3E4A70",
          onSurfaceVariant: "#C3CDEE",
          outline: "#8D99B9",
          outlineVariant: "#3E4A70",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E8EAFF",
          inverseOnSurface: "#1F2949",
          inversePrimary: "#0066CC",
          primaryFixed: "#CCE5FF",
          onPrimaryFixed: "#001F4D",
          primaryFixedDim: "#99CCFF",
          onPrimaryFixedVariant: "#0052B3",
          secondaryFixed: "#D9E2FF",
          onSecondaryFixed: "#001F47",
          secondaryFixedDim: "#ADD8FF",
          onSecondaryFixedVariant: "#0A4FA3",
          tertiaryFixed: "#E0E0FF",
          onTertiaryFixed: "#161C76",
          tertiaryFixedDim: "#C5C6FF",
          onTertiaryFixedVariant: "#3149A8",
          surfaceDim: "#0A0E1F",
          surfaceBright: "#30354D",
          surfaceContainerLowest: "#050909",
          surfaceContainerLow: "#131828",
          surfaceContainer: "#1A2031",
          surfaceContainerHigh: "#25293F",
          surfaceContainerHighest: "#30354D",
        },
        "dark-medium-contrast": {
          primary: "#A3D9FF",
          surfaceTint: "#99CCFF",
          onPrimary: "#001640",
          primaryContainer: "#1A6FDB",
          onPrimaryContainer: "#FFFFFF",
          secondary: "#B8E0FF",
          onSecondary: "#00173A",
          secondaryContainer: "#1B6ECD",
          onSecondaryContainer: "#FFFFFF",
          tertiary: "#D1D2FF",
          onTertiary: "#0B105D",
          tertiaryContainer: "#4B5CB9",
          onTertiaryContainer: "#FFFFFF",
          error: "#FFD2CC",
          onError: "#540003",
          errorContainer: "#FF5449",
          onErrorContainer: "#000000",
          background: "#0A0E1F",
          onBackground: "#E8EAFF",
          surface: "#0A0E1F",
          onSurface: "#FFFFFF",
          surfaceVariant: "#3E4A70",
          onSurfaceVariant: "#D0D9FF",
          outline: "#9FA5C7",
          outlineVariant: "#7B87A8",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#E8EAFF",
          inverseOnSurface: "#14182F",
          inversePrimary: "#0052B3",
          primaryFixed: "#CCE5FF",
          onPrimaryFixed: "#001640",
          primaryFixedDim: "#99CCFF",
          onPrimaryFixedVariant: "#0052B3",
          secondaryFixed: "#D9E2FF",
          onSecondaryFixed: "#00173A",
          secondaryFixedDim: "#ADD8FF",
          onSecondaryFixedVariant: "#0A4FA3",
          tertiaryFixed: "#E0E0FF",
          onTertiaryFixed: "#0B105D",
          tertiaryFixedDim: "#C5C6FF",
          onTertiaryFixedVariant: "#3149A8",
          surfaceDim: "#0A0E1F",
          surfaceBright: "#3C4257",
          surfaceContainerLowest: "#040808",
          surfaceContainerLow: "#181F1F",
          surfaceContainer: "#232929",
          surfaceContainerHigh: "#2D3434",
          surfaceContainerHighest: "#383F3F",
        },
        "dark-high-contrast": {
          primary: "#9BF0CA",
          surfaceTint: "#80D9B8",
          onPrimary: "#000000",
          primaryContainer: "#4BC496",
          onPrimaryContainer: "#000000",
          secondary: "#94F0CF",
          onSecondary: "#000000",
          secondaryContainer: "#4FC59E",
          onSecondaryContainer: "#000000",
          tertiary: "#B0F6B5",
          onTertiary: "#000000",
          tertiaryContainer: "#6CCB72",
          onTertiaryContainer: "#000000",
          error: "#FFECE9",
          onError: "#000000",
          errorContainer: "#FFAEA4",
          onErrorContainer: "#000000",
          background: "#0C1410",
          onBackground: "#DDE7E1",
          surface: "#0C1410",
          onSurface: "#FFFFFF",
          surfaceVariant: "#3E4A45",
          onSurfaceVariant: "#FFFFFF",
          outline: "#E4F0E8",
          outlineVariant: "#B7C3BD",
          shadow: "#000000",
          scrim: "#000000",
          inverseSurface: "#DDE7E1",
          inverseOnSurface: "#000000",
          inversePrimary: "#004F39",
          primaryFixed: "#BFF5DF",
          onPrimaryFixed: "#000000",
          primaryFixedDim: "#80D9B8",
          onPrimaryFixedVariant: "#003825",
          secondaryFixed: "#B6EBD8",
          onSecondaryFixed: "#000000",
          secondaryFixedDim: "#82D7BD",
          onSecondaryFixedVariant: "#003627",
          tertiaryFixed: "#C8F6C9",
          onTertiaryFixed: "#000000",
          tertiaryFixedDim: "#9BDFA0",
          onTertiaryFixedVariant: "#0B2D0E",
          surfaceDim: "#0C1410",
          surfaceBright: "#4C5550",
          surfaceContainerLowest: "#000000",
          surfaceContainerLow: "#1A2420",
          surfaceContainer: "#2C3530",
          surfaceContainerHigh: "#37403B",
          surfaceContainerHighest: "#424B46",
        },
      },
      fontSize: {
        "display-large": [
          "57px",
          {
            lineHeight: "64px",
          },
        ],
        "display-medium": [
          "45px",
          {
            lineHeight: "52px",
          },
        ],
        "display-small": [
          "36px",
          {
            lineHeight: "44px",
          },
        ],
        "headline-large": [
          "32px",
          {
            lineHeight: "40px",
          },
        ],
        "headline-medium": [
          "28px",
          {
            lineHeight: "36px",
          },
        ],
        "headline-small": [
          "24px",
          {
            lineHeight: "32px",
          },
        ],
        "title-large": [
          "22px",
          {
            lineHeight: "28px",
          },
        ],
        "title-medium": [
          "16px",
          {
            lineHeight: "24px",
          },
        ],
        "title-small": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "body-large": [
          "16px",
          {
            lineHeight: "24px",
          },
        ],
        "body-medium": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "body-small": [
          "12px",
          {
            lineHeight: "16px",
          },
        ],
        "label-large": [
          "14px",
          {
            lineHeight: "20px",
          },
        ],
        "label-medium": [
          "12px",
          {
            lineHeight: "16px",
          },
        ],
        "label-small": [
          "11px",
          {
            lineHeight: "16px",
          },
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      screens: {
        custom: "1100px",
        resultaHidden: "766px",
        lgMin: "947px",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("@tailwindcss/typography")],
} satisfies Config;
